### ISSUE TITLE
No module named core

### ISSUE THREAD

**Issue by johndavedosn** [HalilDeniz/TrafficWatch#8]
Hey

I've recently tried the tool but have faced an issue that when I run it it says
```
ModuleNotFoundError: No module named 'core'
```

after doing some debugging it turns out to be an 
issue with the directory structure actually ``traficwatch.py`` should be 
in the root of the repo instead of in ``/app``

**Comment by HalilDeniz** [comment]
Hello, have you set up with setup.py!

**Comment by johndavedosn** [comment]
Yes I did

**Comment by johndavedosn** [comment]
Should I put it on an pull request ?
